[build.environment]
  # to disable npm auto install. see https://community.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759
  NPM_FLAGS="--prefix=/"

[build]
  publish = "dist"
  command = "npx pnpm i && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
